### PR TITLE
Allow ctx to be undefined

### LINKED ISSUE #2: Type for ctx should be Maybe[Catalyst]
If a request is handled entirely within PSGI, then there will be no context. So you should allow for it to be undefined.

It's probably worth not initialising it in that case (since it doesn't make sense to have a context before there have been any requests).

(This is something I came across while doing some testing.)

### PR DESCRIPTION
**Pull request by robrwo**
If a request is handled entirely by Plack, then the context will be
undefined.

Fixes #2.

Note that we probably don't need to make ctx lazily built now.

### CODE REVIEW

**Comment by simbabque** [comment]
Thanks! Would you please add a test for this?

**Comment by robrwo** [comment]
@simbabque Tests done. Waiting for you to merge and release. Thanks.

**Comment by simbabque** [comment]
Thanks a lot! I was busy with the London Perl Workshop, but I will try to get that release out today. I agree that it's ok that the context can be lazy. I will add some more documentation and think again if that deprecation warning is really needed. I might get rid of it. There's no reason to deprecate this thing. We can just leave it in.

**Comment by simbabque** [comment]
Uploaded. Should be there soonish. :)

**Pull request merged**
